### ISSUE TITLE
Provision ROSA GPU cluster using procedural scripts

### ISSUE THREAD

**Issue by butler54** [opendatahub-io-contrib/genai-llm-rag-pattern#47]
- AV to provide which EC2 to provide:
  - G5 instances  

- Bryon deploy ROSA instance
   - central Europe EU Central and EU West

**Comment by bryonbaker** [comment]
@avijra - can you please update this issue with the exact GPUs you need? Please give me a few options.

**Comment by avijra** [comment]
@bryonbaker below are the options 
1. g5.4xlarge x 2
2. P4d instances x2

**Comment by bryonbaker** [comment]
@avijra - I have added 2xg5.4xlarge nodes to the cluster for you. Please validate and let me know.
You never mentioned a disk size so I have used the default of 300GiB

```
$ rosa list machinepools --cluster=2amgteuf5v8aoqumrqmc2tq4a2jmdd7p
ID                      AUTOSCALING  REPLICAS  INSTANCE TYPE  LABELS                                        TAINTS    AVAILABILITY ZONES    SUBNETS    SPOT INSTANCES  DISK SIZE  SG IDs
g5-4xlarge-machinepool  No           2         g5.4xlarge     custom-machine-type=g5-4xlarge-machinepool              us-east-2a                       No              128 GiB    
worker                  No           2         m5.xlarge                                                              us-east-2a                       No              300 GiB
```

Give it a bit for the nodes to be fully provisioned in the cluster.

**Comment by bryonbaker** [comment]
@avijra - ping

**Comment by avijra** [comment]
looks good thanks @bryonbaker. this config is good for the pattern
